### ISSUE TITLE
add minimum attendance.

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-server-next#16]
stark conference room is gonna have a minimum attendance of 6 people, if the attendance is less it shouldn't let you book the room (and send an error)

**Comment by felixruano91** [comment]
Add minimum attendance #18

**Comment by felixruano91** [comment]
- You shoud be able to specify which room will have the minimum guests requirement.
- The minimun amount should have a validation (only numbers, positive and minimum 1).
- It should be define on the schema/model.
- Admins should be the only one with the permission.
