### ISSUE TITLE
get user's bookings

### ISSUE THREAD

**Issue by mishelashala** [ksquareincmx/conference-server-next#24]
We need to create an endpoint that only returns a list of bookings created by the user. The backend should get the user id from the JWT.

**Comment by ghost** [comment]
There is already an endpoint for getting the users bookings
![Screenshot from 2019-09-26 10-40-23](https://user-images.githubusercontent.com/22324337/65703338-38673380-e04a-11e9-8fab-360ef5e10c67.png)
We could use that @mishelashala
