### ISSUE TITLE
Add .env.example and always show mock data

### ISSUE THREAD

**Issue by martiuh** [ksquareincmx/conference-server-next#28]
We need to keep track of what environment variables we use, that's why we need an `.env.example` file, and also for having seed data, we need to display mock data as well.

**Comment by mishelashala** [comment]
Can you list what variables need to be part of the `.env` file, also, can you add it to the `README.md` so people know during the setup process what variables are needed?

**Comment by martiuh** [comment]
Yes, that's a good suggestion, we should add that. as well.
