### ISSUE TITLE
Editing and deleting bookings fail (err. 401)

### ISSUE THREAD

**Issue by eduardomonforte** [ksquareincmx/conference-server-next#33]
User cannot edit and delete bookings at the moment. Console returns a 401 error.

**Comment by jcomoto** [comment]
This sounds like an issue with ACLs or that the app is not handling the ownership of an instance properly.

[This Loopback docks: Defining-and-using-roles](https://loopback.io/doc/en/lb3/Defining-and-using-roles.html#dynamic-roles) may come handy.
